infra:
  pool:
    - name: s1
      ip: 172.20.0.8:22
      username: root
      password: mypassword
    - name: s2
      ip: 172.20.0.3:22
      username: root
      password: mypassword
    - name: s3
      ip: 172.20.0.6:22
      username: root
      password: mypassword
    - name: s4
      ip: 172.20.0.4:22
      username: root
      password: mypassword
    - name: s5
      ip: 172.20.0.5:22
      username: root
      password: mypassword

  resources:
    - name: rabitmq-1
      ip: localhost
      port: 5672
    - name: haproxy-1
      ip: localhost
      port: 9999
    - name: redis-1
      ip: localhost
      port: 6379