version: '3'

services:
  server1:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: galactus_server1
    command: /usr/sbin/sshd -D
    networks:
      - app_net
    ports:
      - 8091:22

  server2:
    container_name: galactus_server2
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/sbin/sshd -D
    networks:
      - app_net
    ports:
      - 8092:22

  server3:
    container_name: galactus_server3
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/sbin/sshd -D
    networks:
      - app_net
    ports:
      - 8093:80

  server4:
    container_name: galactus_server4
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/sbin/sshd -D
    networks:
      - app_net
    ports:
      - 8094:80

  server5:
    container_name: galactus_server5
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/sbin/sshd -D
    networks:
      - app_net
    ports:
      - 8095:80

  server6:
    container_name: galactus_server6
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/sbin/sshd -D
    networks:
      - app_net
    ports:
      - 8096:80

  database:
    container_name: metadb
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=guest
    networks:
      - app_net
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data

  haproxy:
    container_name: haproxy
    image: haproxy:2.7
    volumes:
        - ./haproxy:/haproxy-override
        - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - app_net
    ports:
        - "80:80"
        - "70:70" # haproxy admin console, login with user:pass
        - "9999:9999"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
        - ./prometheus/:/etc/prometheus/
        - prometheus-data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
    networks:
      - app_net
    ports:
        - "9090:9090"
  
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    restart: unless-stopped
    expose:
        - 9093
    networks:
      - app_net
    ports:
        - "9093:9093"
    volumes:
        - "./alertmanager:/config"
        - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
  
  grafana:
    image: grafana/grafana
    networks:
      - app_net
    ports:
        - 3000:3000
    restart: unless-stopped
    volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - grafana-data:/var/lib/grafana

  controller:
    container_name: controller
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/bash","-c"]
    command:
      - java -jar /app/target/*.jar --spring.config.location=file:///app/target/custom.properties
    networks:
      - app_net
    ports:
      - 8080:8080
    volumes:
      - ./target:/app/target
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - server5
      - server6
      - database
      - haproxy

volumes:
  prometheus-data:
  alertmanager-data:
  grafana-data:

networks:
  app_net:
  