global:
  resolve_timeout: 5m

route:
  receiver: webhook
  repeat_interval: 10s
  group_by: ['...']
  routes:
  - receiver: webhook

receivers:
- name: webhook
  webhook_configs:
  - url: http://controller:8080/v1/alert/
    send_resolved: false
    # http_config:
    #   bearer_token: your-bearer-token
    #   tls_config:
    #     insecure_skip_verify: true


# route:
#   group_by: ['job']
#   group_wait: 1s
#   group_interval: 5m
#   repeat_interval: 12h
#   receiver: webhook
#   routes:
#   - receiver: webhook
#     continue: true  

# receivers:
#     - name: webhook
#       webhook_configs:
#       - url: 'http://localhost:8088/v1/service/alert'
#       - send_resolved: true
#       - max_alerts: 1




    #   basic_auth:
    #     username: your-username
    #     password: your-password